// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/Foo/index":{"id":"components/Foo/index","path":"components/foo","parentId":"DocLayout"},"components/TimePicker/index":{"id":"components/TimePicker/index","path":"components/time-picker","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}},
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'C:/Users/admin/Desktop/实战/RomanticUI/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'C:/Users/admin/Desktop/实战/RomanticUI/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'C:/Users/admin/Desktop/实战/RomanticUI/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'C:/Users/admin/Desktop/实战/RomanticUI/docs/index.md')),
'components/Foo/index': React.lazy(() => import(/* webpackChunkName: "Foo__index.md" */'C:/Users/admin/Desktop/实战/RomanticUI/src/Foo/index.md')),
'components/TimePicker/index': React.lazy(() => import(/* webpackChunkName: "TimePicker__index.md" */'C:/Users/admin/Desktop/实战/RomanticUI/src/TimePicker/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'C:/Users/admin/Desktop/实战/RomanticUI/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
