// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Users/admin/Desktop/实战/RomanticUI/node_modules/dumi/theme-default/slots/Features/index.js';
