export { default as Avatar } from './Avatar';
export { default as Divider } from './Divider';
export * as Word from './Docx';
export { default as Menu, type AllItems } from './Menu';
export { default as Pagination } from './Pagination';
export { default as ProgressBar } from './ProgressBar';
export { default as Spin } from './Spin';
export { default as SvgIcon } from './SvgIcon';
export { default as Table } from './Table';
export { default as Tabs } from './Tabs';
export { default as Watermark } from './WaterMark';
